@api_base_url = http://127.0.0.1:8000/api

###
# Get User XP
###
GET {{api_base_url}}/user-progress/1/xp
Accept: application/json

###

###
# Add XP to User
###
POST {{api_base_url}}/user-progress/1/xp/add/50
Accept: application/json

###

###
# Reset User XP
###
POST {{api_base_url}}/user-progress/1/xp/reset
Accept: application/json