api_platform:
    title: "My Dummy API"
    version: 1.0.0
    description: |
        This is a test API.
        Made with love
    use_symfony_listeners: true
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
