@api_base_url = http://127.0.0.1:8000/api

###
# Create User with Progress
###
POST {{api_base_url}}/user/create/testuser
Content-Type: application/json
Accept: application/json

{
  "username": "testuser"
}